# Generated by Django 5.1.7 on 2025-04-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningpath',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='learningpath',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='path_data',
            field=models.JSONField(default=dict),
        ),
    ]
