# Generated by Django 5.1.7 on 2025-04-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0002_alter_learningpath_options_learningpath_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='learningpath',
            table='path_learningpath',
        ),
    ]
