# Generated by Django 5.1.7 on 2025-04-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0003_alter_learningpath_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='path_data',
            field=models.JSONField(),
        ),
        migrations.AlterModelTable(
            name='learningpath',
            table=None,
        ),
    ]
