# Generated by Django 5.1.7 on 2025-04-05 23:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='badge',
            name='points_required',
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('achievement', 'Achievement'), ('milestone', 'Milestone'), ('skill', 'Skill')], default='achievement', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='badge',
            name='criteria',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='badge',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='badge',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
